In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('IndianFoodDataset3.csv',index_col=None)

In [4]:
#df = df.drop(['Unnamed: 0',	'Unnamed: 0.1',	'Unnamed: 0.1.1'],axis = 1)
df = df.drop(['Unnamed: 0',	'Unnamed: 0.1'],axis = 1)

In [5]:
df

,Unnamed: 0.2,RecipeName,Ingredients,Course,Instructions
0,0,Hù Tiéu,"['dry rice noodles medium size', 'Hù Tiéu soup...",Breakfast,['Cook rice noodles according to package instr...
1,1,Hù Tiéu,"['dry rice noodles medium size', 'Hù Tiéu soup...",Breakfast,['Cook rice noodles according to package instr...
2,2,Donzelle,"['500 g 00 flour', '1 Tbsp sugar', '1 Tbsp sal...",Snack,['Place the flour into the bowl of a food mixe...
3,3,Albaloo Polo,"['2 cups Basmati Rice', '2 tbsp Salt', '1/8 ts...",Dinner,"['Place the sour cherries in a saucepan, add s..."
4,4,Batatinha em Conserva,"['1 can cooked baby potatoes', '1 small onion ...",Snack,['Drain and rinse canned potatoes. Set aside.'...
...,...,...,...,...,...
133,133,Pastina,"['1 box pastina pasta', 'parmesan cheese grate...",Dinner,['Cook pastina according to package instructio...
134,134,Kakadiche Dhirde,"['1 cup Grated Cucumber', '1 tsp Crushed Green...","Lunch, Snack","['Grate your cucumber on a medium grate', 'Add..."
135,135,Espagueti Verde,"['3 medium-large poblano peppers', '1 chicken ...",Dinner,['Roast the peppers either directly on the fla...
136,136,Gombotz,"['1 lb starchy potatoes', '1 egg', '1 Tbsp but...","Dessert, Dinner","['Boil the potatoes with their skin on, until ..."
137,137,Pink Beetroot Pasta,"['8 oz long pasta', 'cooked beets fresh or can...",Dinner,['Cook pasta according to package instructions...

In [6]:
df2 = df.drop_duplicates('RecipeName')

In [7]:
df2

,Unnamed: 0.2,RecipeName,Ingredients,Course,Instructions
0,0,Hù Tiéu,"['dry rice noodles medium size', 'Hù Tiéu soup...",Breakfast,['Cook rice noodles according to package instr...
2,2,Donzelle,"['500 g 00 flour', '1 Tbsp sugar', '1 Tbsp sal...",Snack,['Place the flour into the bowl of a food mixe...
3,3,Albaloo Polo,"['2 cups Basmati Rice', '2 tbsp Salt', '1/8 ts...",Dinner,"['Place the sour cherries in a saucepan, add s..."
4,4,Batatinha em Conserva,"['1 can cooked baby potatoes', '1 small onion ...",Snack,['Drain and rinse canned potatoes. Set aside.'...
5,5,Macarrão Misturado,"['200 g milk', '1 Tbsp butter', '1 Tbsp flour'...",Dinner,"['In a pan, melt the butter and slowly add the..."
...,...,...,...,...,...
133,133,Pastina,"['1 box pastina pasta', 'parmesan cheese grate...",Dinner,['Cook pastina according to package instructio...
134,134,Kakadiche Dhirde,"['1 cup Grated Cucumber', '1 tsp Crushed Green...","Lunch, Snack","['Grate your cucumber on a medium grate', 'Add..."
135,135,Espagueti Verde,"['3 medium-large poblano peppers', '1 chicken ...",Dinner,['Roast the peppers either directly on the fla...
136,136,Gombotz,"['1 lb starchy potatoes', '1 egg', '1 Tbsp but...","Dessert, Dinner","['Boil the potatoes with their skin on, until ..."
137,137,Pink Beetroot Pasta,"['8 oz long pasta', 'cooked beets fresh or can...",Dinner,['Cook pasta according to package instructions...

In [8]:
df2.to_csv('IndianFoodDataset4.csv')